name: CI

on:
  pull_request:
  push:
    branches:
      - development
      - release

jobs:
  build:
    name: Compile The Crate
    runs-on: ubuntu-latest

    steps:
      # Checkout the current code from github into the CI machine
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Rust Nightly and Cargo
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: rustfmt, clippy, rust-src, llvm-tools-preview
          target: aarch64-unknown-none

      - name: Install Cargo Make
        uses: davidB/rust-cargo-make@v1
        with:
          version: 'latest'

      - name: Remove patches if not a PR build
        run: sed -i "/{^\[patch\.crates-io\] /{:a;N;/\Z}/!ba};/^ruspiro-.*\(git\|path\).*/d" Cargo.toml;
        if: ${{ github.event_name != 'pull_request' }}

      - name: Compile
        run: cargo make pi3

